### ISSUE TITLE
Cria DAO do usuário

### ISSUE THREAD

**Issue by erivanbarbosa** [erivanbarbosa/Livraria-Laboratorio#10]

**Comment by erivanbarbosa** [comment]
Criar a classe DAO do usuário com um método que recebe um Usuário e verifica se existe no banco um usuário com o mesmo nome e senha.

**Comment by erivanbarbosa** [comment]
O Rubens iniciou seu trabalho por engano. Você pode consultar o que foi feito em: https://github.com/erivanbarbosa/Livraria-Laboratorio/pull/14

Observar os comentários que deixei.

**Comment by emiliaelizabeth** [comment]
Olá Pessoal! Movi a tarefa de "To Do", para "Done" e só depois de futricar um pouco o ambiente do git, percebi que a tarefa não estava atribuída a mim, porém Marcos e eu fizemos há dois sábados atrás!
Será que estou perdida!? Qualquer coisa, corrige aí Erivan!
